### ISSUE TITLE
Task list item on hovering has the same background and text color

### ISSUE THREAD

**Issue by TifPun** [cquanu/github-dark#36] opened 2016-11-23 20:13 UTC
#### What's the issue:
When hovering on a `task-list-item`, the background color and the text color are the same, making the text not readable
 
#### Steps to reproduce:

Create a task list like the one below, then hover over a list item:

```md
__Methods__
- [ ] mapWidgetAdded
- [ ] mapWidgetRemoved
- [ ] toolbarDrawComplete
```

#### Screenshots:
![image](https://cloud.githubusercontent.com/assets/4983864/20577100/a185106e-b175-11e6-8677-148398722485.png)

#### Solutions:
Might be a workaround, I just added the following style for task-list-item on the hover state within the `/* Repo | Issues Tab */` section

```css
.task-list-item:hover {
	color: #000
}
```

it produces the following result: 

![image](https://cloud.githubusercontent.com/assets/4983864/20577158/e89e17a2-b175-11e6-8cbd-cb57ad1b0013.png)

#### What version is affected by this problem:

GitHub Dark v2.5.0

#### Thanks
Thank for providing this great stylesheet. Keep up the good work!

**Comment by cquanu** [comment] 2016-12-21 02:00
@TifPun Hi, thanks for helping! Where can i find the task list?

**Comment by cquanu** [comment] 2016-12-21 03:01
MB. Just saw the steps to reproduce this bug

**Comment by cquanu** [comment] 2016-12-21 03:01
Test
- [ ] mapWidgetAdded
- [ ] mapWidgetRemoved
- [ ] toolbarDrawComplete

**Comment by cquanu** [comment] 2016-12-21 03:09
This will be fixed in the next update. Thanks!

**Comment by TifPun** [comment] 2017-03-08 16:22
Thanks @cquanu for your quick response! Great job and please keep it up :)

**Comment by snowe2010** [comment] 2017-10-26 19:03
I'm currently still seeing this broken. the css I added to fix it is

```css
reorderable-task-lists .markdown-body .task-list-item.hovered {
    background: #243447;
    border-top-color: #ededed;
    border-bottom-color: #ededed;
}
```

all i did was change background to your current secondary color (the bar color for comments etc)

**Comment by locness3** [comment] 2018-07-16 11:17
You should open a pull request

**Comment by snowe2010** [comment] 2018-07-16 16:00
@locness3 I actually am now a contributor to the project. I will fix it in a bit.

**Comment by snowe2010** [comment] 2018-07-16 16:50
@locness3 This was already fixed in a previous commit. You might not be seeing this in your version because Quan temporarily handed control of the project over to me, but I do not have permission to update the userstyles.org version. You can receive all updates by using the Stylus addon and using the userstyle version of the css file. You can either create the userstyle on your own, or you can open the file directly with the extension already installed and it should prompt you to install it. Just visit this link. 

https://raw.githubusercontent.com/cquanu/github-dark/master/github-dark.user.css

**Closed by snowe2010** 2018-07-16 16:50 UTC
Labels: willfix

**Comment by locness3** [comment] 2018-07-17 04:55
@snowe2010 OK
